package com.example.quoteapp

import retrofit2.http.GET
import retrofit2.Response

interface API_Interface {

    /*"@GET" ANNOTATION SPECIFIES THAT THIS METHOD CORRESPONDS TO AN HTTP "GET" REQUEST.
    THE STRING "random" REPRESENTS THE RELATIVE ENDPOINT FOR THIS REQUEST.
    THE "BASE_URL" IS "https://zenquotes.io/api/".
    NOW, THE FINAL URL WILL BE "https://zenquotes.io/api/random". */
    
    @GET("random")
    suspend fun getRandomQuote() : Response<List<Quote>>
    
    /*"suspend" KEYWORD MARKS THE METHOD AS A SUSPENDING FUNCTION, WHICH ALLOWS IT TO BE
    CALLED WITHIN A KOTLIN COROUTINE. "suspend" ENSURES THAT THIS METHOD WILL NOT BLOCK THE MAIN THREAD.
    "Response<>" ENCAPSULATES BOTH THE HTTP RESPONSE AND METADETA (LIKE STATUS CODE, HEADERS), AND
    ALLOWS THE HANDLING OF BOTH SUCCESS AND FAILURE CASES.
    "List<Quote> INDICATES THE API RESPONSE IS EXPECTED TO BE A LIST OF "Quote" OBJECTS.*/
}
